---
## Author
author:
  name: Кара Егор Андреевич
  degrees: student
  email: 1032253851@rudn.ru
  affiliation:
    - name: Российский университет дружбы народов
      country: Российская Федерация
      postal-code: 117198
      city: Москва
      address: ул. Миклухо-Маклая, д. 6

## Title
title: "Система инициализации Upstart"
subtitle: "Реферат по дисциплине 'Операционные системы'"
license: "CC BY"

bibliography: refs.bib
---

# Цель работы

Изучить архитектутру, принципы работы и особенности системы инициализиции Upstart, а также сранить её с классической системы SysV init и определить её место в эволюции init-систем Linux

# Задание

1. Изучить историю появления Upstart.
2. Рассмотреть архитектуру и событийную модель.
3. Проанализировать конфигурационные файлы и механизм запуска служб.
4. Сравнить Upstart c SysV init.
5. Подготовить выводы о значимости Upstart в развитии Linux-систем.

# Теоретическое введение

Система инициализации Upstart была разработана компанией Сanonical в 2006 году как замена традиционной последовательной системе SysV init. Основная идея Upstart - переход к событийной модели, позволяющей запускать и останавливать службы в ответ на изменения состояния системы.

Upstart использует асинхронный запуск процессов, что ускоряет загрузку и делает систему более гибкой. Конфигурационные файлы Upstart распологаются в каталоге /etc/init/ и имеют расширение .conf.

| Характеристика          | SysV init        | Upstart        |
|-------------------------|------------------|----------------|
| Модель работы           | Последовательная | Событийная     |
| Запуск служб            | Синхронный       | Асинхронный    |
| Реакция на события      | Нет              | Да             |
| Поддержка старых скриптов | Да             | Да             |

: Сравнение SysV init и Upstart
{#tbl-compare}

Более подробно о системах инициализации см. [@upstart-wiki; @upstart-man; @upstart-ubuntu].

# Выполнение работы

## Архитектура Upstart

Upstart основан на событийной модели. События могут быть:

- системный (startup, shutdown);
- связанным с оборудованием (device-added, device-removed);
- связанными с состоянием служб (started, stopped)
- пользовательским (создаваемыми вручную).

Пример конфигурационного файла:

```conf
start on runlevel [2345]
stop on runlevel [!2345]
respawn
exec /usr/bin/myservice --daemon

# Выводы

В ходе работы были изучены архитектура и принципы функционирования системы инициализации Upstart. 
Показано, что переход к событийной модели позволил повысить гибкость управления службами 
и ускорить процесс загрузки операционной системы. Несмотря на замену Upstart системой systemd, 
его идеи продолжают влиять на развитие современных init‑систем.

# Список литературы {.unnumbered}

::: {#refs}
:::



